export const AUTH_START = "APP/AUTH_START"
export const AUTH_SUCCESS = "APP/AUTH_SUCCESS"
export const AUTH_FAIL = "APP/AUTH_FAIL"

export const SIGNUP_START = "SIGNUP/START"
export const SIGNUP_SUCCESS = "SIGNUP/SUCCESS"
export const SIGNUP_FAIL = "SIGNUP/FAIL"
export const SIGNUP_RECOVER_FROM_FAILURE = "SIGNUP/RECOVER_FROM_FAILURE"

