export const AUTH_START = "APP/AUTH_START";
export const AUTH_SUCCESS = "APP/AUTH_SUCCESS";
export const AUTH_FAIL = "APP/AUTH_FAIL";
export const AUTH_RESET_STATE = "APP/AUTH_RESET_STATE";

export const SIGNUP_START = "SIGNUP/START";
export const SIGNUP_SUCCESS = "SIGNUP/SUCCESS";
export const SIGNUP_FAIL = "SIGNUP/FAIL";
export const SIGNUP_RECOVER_FROM_FAILURE = "SIGNUP/RECOVER_FROM_FAILURE";

export const PAINEL_FETCH_SEASONS_START = "PAINEL/FETCH_SEASONS_START";
export const PAINEL_FETCH_SEASONS_SUCCESS = "PAINEL/FETCH_SEASONS_SUCCESS";
export const PAINEL_FETCH_SEASONS_FAIL = "PAINEL/FETCH_SEASONS_FAIL";

export const PAINEL_SELECT_SEASON = "PAINEL/SEASON_SELECTED";
export const PAINEL_UNSELECT_SEASON = "PAINEL/SEASON_UNSELECTED";

export const PAINEL_CREATE_SEASON_STARTED = "PAINEL/CREATE_SEASON_STARTED";
export const PAINEL_CREATE_SEASON_SUCCESS = "PAINEL/CREATE_SEASON_SUCCESS";
export const PAINEL_CREATE_SEASON_FAILED = "PAINEL/CREATE_SEASON_FAILED";

export const PAINEL_UPDATE_SEASON_STARTED = "PAINEL/UPDATE_SEASON_STARTED";
export const PAINEL_UPDATE_SEASON_SUCCESS = "PAINEL/UPDATE_SEASON_SUCCESS";
export const PAINEL_UPDATE_SEASON_FAILED = "PAINEL/UPDATE_SEASON_FAILED";

export const PAINEL_DELETE_SEASON_STARTED = "PAINEL/DELETE_SEASON_STARTED";
export const PAINEL_DELETE_SEASON_SUCCESS = "PAINEL/DELETE_SEASON_SUCCESS";
export const PAINEL_DELETE_SEASON_FAILED = "PAINEL/DELETE_SEASON_FAILED";

export const PAINEL_SELECT_GAME = "PAINEL/GAME_SELECTED";
export const PAINEL_UNSELECT_GAME = "PAINEL/GAME_UNSELECTED";

export const PAINEL_FETCH_GAMES_START = "PAINEL/FETCH_GAMES_START";
export const PAINEL_FETCH_GAMES_SUCCESS = "PAINEL/FETCH_GAMES_SUCCESS";
export const PAINEL_FETCH_GAMES_FAIL = "PAINEL/FETCH_GAMES_FAIL";

export const PAINEL_CREATE_GAME_START = "PAINEL/CREATE_GAME_START";
export const PAINEL_CREATE_GAME_SUCCESS = "PAINEL/CREATE_GAME_SUCCESS";
export const PAINEL_CREATE_GAME_FAILED = "PAINEL/CREATE_GAME_FAILED";

export const PAINEL_UPDATE_GAME_START = "PAINEL/UPDATE_GAME_START";
export const PAINEL_UPDATE_GAME_SUCCESS = "PAINEL/UPDATE_GAME_SUCCESS";
export const PAINEL_UPDATE_GAME_FAILED = "PAINEL/UPDATE_GAME_FAILED";

export const PAINEL_DELETE_GAME_START = "PAINEL/DELETE_GAME_START";
export const PAINEL_DELETE_GAME_SUCCESS = "PAINEL/DELETE_GAME_SUCCESS";
export const PAINEL_DELETE_GAME_FAILED = "PAINEL/DELETE_GAME_FAILED";

export const PAINEL_ADD_GAME_TO_TRASH_LIST = "PAINEL/ADD_GAME_TO_TRASH_LIST";
export const PAINEL_REMOVE_GAME_FROM_TRASH_LIST = "PAINEL/REMOVE_GAME_FROM_TRASH_LIST";

export const PAINEL_ADD_SEASON_TO_TRASH_LIST = "PAINEL/ADD_SEASON_TO_TRASH_LIST";
export const PAINEL_REMOVE_SEASON_FROM_TRASH_LIST = "PAINEL/REMOVE_SEASON_FROM_TRASH_LIST";

export const PAINEL_REFRESH_TABLE_DATA = "PAINEL/REFRESH_TABLE_DATA";

export const PAINEL_OPEN_DIALOGUE_FORM = "PAINEL/OPEN_DIALOGUE_FORM";
export const PAINEL_CLOSE_DIALOGUE_FORM = "PAINEL/CLOSE_DIALOGUE_FORM";

export const PAINEL_CLEAN_GAMES = "PAINEL/CLEAN_GAMES";

export const PAINEL_LOGOUT = "PAINEL/LOGOUT";

