export const AUTH_START = "APP/AUTH_START";
export const AUTH_SUCCESS = "APP/AUTH_SUCCESS";
export const AUTH_FAIL = "APP/AUTH_FAIL";
export const AUTH_RESET_STATE = "APP/AUTH_RESET_STATE"

export const SIGNUP_START = "SIGNUP/START";
export const SIGNUP_SUCCESS = "SIGNUP/SUCCESS";
export const SIGNUP_FAIL = "SIGNUP/FAIL";
export const SIGNUP_RECOVER_FROM_FAILURE = "SIGNUP/RECOVER_FROM_FAILURE";

export const PAINEL_CREATE_SEASON = "PAINEL/CREATE_SEASON";
export const PAINEL_UPDATE_SEASON = "PAINEL/UPDATE_SEASON";
export const PAINEL_DELETE_SEASON = "PAINEL/DELETE_SEASON";
export const PAINEL_CREATE_GAME = "PAINEL/CREATE_GAME";
export const PAINEL_UPDATE_GAME = "PAINEL/UPDATE_GAME";
export const PAINEL_DELETE_GAME = "PAINEL/DELETE_GAME"
export const PAINEL_REFRESH_TABLE_DATA = "PAINEL/REFRESH_TABLE_DATA"
export const PAINEL_CRUD_START = "PAINEL/CRUD_START";
export const PAINEL_CRUD_SUCCESS = "PAINEL/CRUD_SUCCESS";
export const PAINEL_CRUD_FAILED = "PAINEL/CRUD_FAILED";
export const PAINEL_OPEN_DIALOGUE_FORM = "PAINEL/OPEN_DIALOGUE_FORM"
export const PAINEL_CLOSE_DIALOGUE_FORM = "PAINEL/CLOSE_DIALOGUE_FORM"

